services:
  registry:
    image: registry:2
    container_name: registry
    restart: unless-stopped
    ports:
      - "5050:5000"
    volumes:
      - registry-data:/var/lib/registry
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    networks:
      - dockercd-net

volumes:
  registry-data:

networks:
  dockercd-net:
    external: true
