apiVersion: dockercd/v1
kind: Application
metadata:
  name: autonops
spec:
  source:
    repoURL: https://github.com/mkolb22/autonops.git
    targetRevision: main
    path: .
    composeFiles:
      - docker-compose.yml
  destination:
    dockerHost: unix:///var/run/docker.sock
    projectName: autonops
  syncPolicy:
    automated: true
    prune: true
    selfHeal: true
    pollInterval: 180s
