apiVersion: dockercd/v1
kind: Application
metadata:
  name: infra
spec:
  source:
    repoURL: https://github.com/mkolb22/dockercd.git
    targetRevision: main
    path: applications/infra/
    composeFiles:
      - docker-compose.yml
  destination:
    dockerHost: unix:///var/run/docker.sock
    projectName: infra
  syncPolicy:
    automated: true
    prune: true
    selfHeal: true
    pollInterval: 180s
