apiVersion: dockercd/v1
kind: Application
metadata:
  name: registry
spec:
  source:
    repoURL: http://gitea:3000/dockercd/dockercd.git
    targetRevision: main
    path: applications/registry/
    composeFiles:
      - docker-compose.yml
  destination:
    dockerHost: unix:///var/run/docker.sock
    projectName: registry
  syncPolicy:
    automated: true
    prune: true
    selfHeal: true
    pollInterval: 180s
