apiVersion: dockercd/v1
kind: Application
metadata:
  name: uptime-kuma
spec:
  source:
    repoURL: https://github.com/mkolb22/dockercd.git
    targetRevision: main
    path: applications/uptime-kuma/
    composeFiles:
      - docker-compose.yml
  destination:
    dockerHost: unix:///var/run/docker.sock
    projectName: uptime-kuma
  syncPolicy:
    automated: true
    prune: true
    selfHeal: true
    pollInterval: 180s
