/**
 * koan-observe: Prompt and workflow observability analysis.
 *
 * Analyzes prompt logs to show token usage, concept breakdown, and session patterns.
 */

import { Command } from 'commander';
import chalk from 'chalk';
import { requireProjectRoot, wrapCliAction, parseRelativeDate } from '@zen/koan-core';
import {
  loadPromptLogs,
  loadDailyStats,
  filterLogs,
  analyzePromptLogs,
} from './analyzer.js';
import { formatAnalysis, formatDailyStats, formatEmptyState } from './formatter.js';
import type { CliOptions } from './types.js';

export function createObserveCommand(): Command {
  const cmd = new Command('observe')
    .description('Prompt and workflow observability analysis')
    .version('1.0.0');

  // Main analysis command
  cmd
    .command('analyze', { isDefault: true })
    .description('Analyze prompt logs')
    .option('--from <date>', 'Filter from date (ISO or relative like 7d, 24h)')
    .option('--to <date>', 'Filter until date')
    .option('-c, --concept <name>', 'Filter to specific concept')
    .option('--format <type>', 'Output format: table (default), json', 'table')
    .action(wrapCliAction(async (options: CliOptions) => {
      const projectRoot = requireProjectRoot();

      // Load logs
      const logs = loadPromptLogs(projectRoot);

      if (logs.length === 0) {
        console.log(formatEmptyState());
        process.exit(0);
      }

      // Apply filters
      const filterOptions: { from?: Date; to?: Date; concept?: string } = {};

      if (options.from) {
        filterOptions.from = parseRelativeDate(options.from);
      }

      if (options.to) {
        filterOptions.to = parseRelativeDate(options.to);
      }

      if (options.concept) {
        filterOptions.concept = options.concept;
      }

      const filteredLogs = filterLogs(logs, filterOptions);

      if (filteredLogs.length === 0) {
        console.log(chalk.yellow('No logs match the specified filters.'));
        process.exit(0);
      }

      // Analyze
      const analysis = analyzePromptLogs(filteredLogs);

      // Output
      if (options.format === 'json') {
        console.log(JSON.stringify(analysis, null, 2));
      } else {
        console.log(formatAnalysis(analysis));
      }
    }));

  // Today's stats command
  cmd
    .command('today')
    .description('Show today\'s prompt statistics')
    .action(wrapCliAction(async () => {
      const projectRoot = requireProjectRoot();

      const stats = loadDailyStats(projectRoot);

      if (!stats) {
        console.log(chalk.yellow('No daily stats available.'));
        console.log(chalk.gray('Stats are generated by the post-prompt-observe hook.'));
        process.exit(0);
      }

      console.log(formatDailyStats(stats));
    }));

  // Concepts summary command
  cmd
    .command('concepts')
    .description('Show token usage by concept')
    .option('--from <date>', 'Filter from date')
    .action(wrapCliAction(async (options: { from?: string }) => {
      const projectRoot = requireProjectRoot();

      const logs = loadPromptLogs(projectRoot);

      if (logs.length === 0) {
        console.log(formatEmptyState());
        process.exit(0);
      }

      const filterOptions: { from?: Date } = {};
      if (options.from) {
        filterOptions.from = parseRelativeDate(options.from);
      }

      const filteredLogs = filterLogs(logs, filterOptions);
      const analysis = analyzePromptLogs(filteredLogs);

      console.log(chalk.cyan.bold('Token Usage by Concept'));
      console.log(chalk.gray('━'.repeat(50)));
      console.log(
        chalk.gray(
          `${'Concept'.padEnd(20)} ${'Calls'.padStart(8)} ${'Tokens'.padStart(12)} ${'Avg'.padStart(8)}`
        )
      );
      console.log(chalk.gray('─'.repeat(50)));

      for (const stat of analysis.by_concept) {
        const concept = stat.concept.padEnd(20);
        const calls = stat.calls.toLocaleString().padStart(8);
        const tokens = stat.tokens.toLocaleString().padStart(12);
        const avg = stat.avg_tokens.toLocaleString().padStart(8);
        console.log(`${concept} ${calls} ${tokens} ${avg}`);
      }

      console.log(chalk.gray('━'.repeat(50)));
      console.log(
        `${'Total'.padEnd(20)} ${analysis.total_calls.toLocaleString().padStart(8)} ${analysis.total_tokens.toLocaleString().padStart(12)}`
      );
    }));

  // Sessions summary command
  cmd
    .command('sessions')
    .description('Show session summaries')
    .option('-n, --limit <count>', 'Number of sessions to show', '10')
    .action(wrapCliAction(async (options: { limit?: string }) => {
      const projectRoot = requireProjectRoot();

      const logs = loadPromptLogs(projectRoot);

      if (logs.length === 0) {
        console.log(formatEmptyState());
        process.exit(0);
      }

      const analysis = analyzePromptLogs(logs);
      const limit = parseInt(options.limit || '10', 10);

      console.log(chalk.cyan.bold('Sessions by Token Usage'));
      console.log(chalk.gray('━'.repeat(70)));

      for (const session of analysis.top_sessions.slice(0, limit)) {
        const id = session.session_id.slice(0, 12);
        const tokens = session.tokens.toLocaleString().padStart(8);
        const calls = session.calls;
        const concepts = session.concepts.join(', ');

        console.log(`${chalk.yellow(id)} │ ${tokens} tokens │ ${calls} calls`);
        console.log(`             │ ${chalk.gray('Concepts:')} ${concepts}`);
        console.log(chalk.gray('─'.repeat(70)));
      }
    }));

  return cmd;
}
