services:
  code-server:
    image: codercom/code-server:latest
    container_name: code-server
    restart: unless-stopped
    ports:
      - "8443:8080"
    volumes:
      - code-server-data:/home/coder
    environment:
      PASSWORD: dockercd
    networks:
      - dockercd-net

volumes:
  code-server-data:

networks:
  dockercd-net:
    external: true
